-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvFSHFKd+n18nMim4
G+CznsXR1UTqYJYcKTAf8qLMO46gCgYIKoZIzj0DAQehRANCAARNa67kdnsPDoZp
uMyljQgNTZcijm2nGedCLfviUYt39EoSkysBJdcyufp5LT4V/GOjU6QsLzYrAthl
H+6qKzz9
-----END PRIVATE KEY-----